server.port: 8888
spring:
  application:
    name: cloudserver
  cloud:
    config:
      server:
        git:
#          uri: ${GIT_SCCS}
          uri: https://github.com/mlaciak/Cloudrepo
          username: ${GIT_USERN}
          password: ${GIT_PASSWD}
          searchPaths: /*